SpodIglyMVC/SpodIglyMVC/Controllers/StoreController.cs
using SpodIglyMVC.DAL;
using SpodIglyMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;

namespace SpodIglyMVC.Controllers
{
    public class StoreController : Controller
    {
        StoreContext db = new StoreContext();
        // GET: Store
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Details(int id)
        {
            var album = db.Albums.Find(id);

            return View(album);
        }

        public ActionResult List(string genrename, string searchQuery = null)
        {
            var genre = db.Genres.Include("Albums").Where(g => g.Name.ToUpper() == genrename.ToUpper()).Single();
            var albums = genre.Albums.Where(a => (searchQuery == null ||
                                                a.AlbumTitle.ToLower().Contains(searchQuery.ToLower()) ||
                                                a.ArtistName.ToLower().Contains(searchQuery.ToLower())) &&
                                                !a.IsHidden);

            if (Request.IsAjaxRequest())
            {
                return PartialView("_ProductList", albums);
            }


            return View(albums);
        }

        [ChildActionOnly]
        [OutputCache(Duration = 80000)]
        public ActionResult GenresMenu()
        {
            var genres = db.Genres.ToList();

            return PartialView("_GenresMenu", genres);
        }

        public ActionResult AlbumsSuggestions(string term)
        {
            var albums = this.db.Albums.Where(a => a.AlbumTitle.ToLower().Contains(term.ToLower()) && !a.IsHidden).Take(5).Select(a => new { label = a.AlbumTitle });

            return Json(albums, JsonRequestBehavior.AllowGet);
        }
    }
}

SpodIglyMVC/SpodIglyMVC/Controllers/ViewSwitcherController.cs
using System.Web.Mvc;
using System.Web.WebPages;

namespace SpodIglyMVC.Controllers
{
    public class ViewSwitcherController : Controller
    {
        public RedirectResult SwitchView(bool mobile, string returnUrl) {
            if (Request.Browser.IsMobileDevice == mobile)
                HttpContext.ClearOverriddenBrowser();
            else
                HttpContext.SetOverriddenBrowser(mobile ? BrowserOverride.Mobile : BrowserOverride.Desktop);

            return Redirect(returnUrl);
        }
    }
}

SpodIglyMVC/SpodIglyMVC/Views/Shared/_Layout.Mobile.cshtml
<!DOCTYPE html> 
<html> 
    <head> 
        <meta charset="utf-8" />
        <title>@ViewBag.Title</title> 
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/Mobile/css", "~/Content/jquerymobile/css")
        @Scripts.Render("~/bundles/jquery", "~/bundles/jquerymobile")
        <script>
            $(document).ready(function () {
                $.mobile.ajaxEnabled = false; 
            });
        </script>
    </head> 
<body> 

    <div data-role="page" data-theme="a">
        @Html.Partial("_ViewSwitcher")

        <div data-role="header">
            <h1>@ViewBag.Title</h1>
        </div>

        <div data-role="content">
            @RenderSection("featured", false)
            @RenderBody()		
        </div>

    </div>

</body>
</html>

SpodIglyMVC/SpodIglyMVC/Views/Shared/_RightSectionLayout.cshtml
@{
    Layout = "~/Views/Shared/_StoreLayout.cshtml";
}

<div id="productlist-content">

    @Html.Action("GenresMenu", "Store")

    <div id="productlist-rightsection">
        <div id="breadcrumb-section">
            <img src="@Url.Content("~/Content/Images/home-small.png")" />
            @Html.MvcSiteMap().SiteMapPath()
        </div>
        <section class="content-section">
            <div class="section-header" style="margin-bottom: 0px">
                <h1>
                    @RenderSection("SectionTitle", required: false)
                </h1>
            </div>

            @RenderBody()
        </section>
    </div>
</div>

@section ScriptsBottom{
    @RenderSection("ScriptsBottom", required: false)
}

SpodIglyMVC/SpodIglyMVC/Views/Shared/_StoreLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" />
    <title>@ViewBag.Title</title>

    @System.Web.Optimization.Styles.Render("~/Content/themes/base/css")
</head>
<body>
    <header>
        <div style="overflow: hidden;">
            <a id="facebook-header" href="">
                DOŁĄCZ DO 1500 FANÓW NA FB
            </a>

            <a id="cart-header-link" href="@Url.Action("Index","Cart")">
                KOSZYK (<span id="cart-header-items-count">
                    @Html.Action("GetCartItemsCount", "Cart")
                </span>)
                <span id="cart-header-logo"></span>
            </a>

            @Html.Partial("_LoginPartial")

        </div>
        <a id="main-header-logo" href="@Url.Content("~/")">
            <img src="../Content/Images/spodigly-logo-main.png" class="center" />
        </a>
    </header>

    <div>
        @RenderBody()
    </div>

    <footer>
        <nav>
            <ul>
                <li><a href="">O nas</a></li>
                <li><a href="@Url.Action("StaticContent", "Home", new { viewname = "Kontakt" })">Kontakt</a></li>
                <li><a href="">Wysyłka</a></li>
                <li><a href="">Regulamin</a></li>
            </ul>
        </nav>
        <div id="footer-cd-logo">
            <img src="@Url.Content("~/content/images/footer-cd.png")" />
        </div>

        <div id="footer-copyright">
            Copyright &copy; 2013 Spod Igły
        </div>
    </footer>
    @RenderSection("ScriptsBottom", required: false)

</body>
</html>

SpodIglyMVC/SpodIglyMVC/Views/Shared/_ViewSwitcher.cshtml
@if (Request.Browser.IsMobileDevice && Request.HttpMethod == "GET")
{
    <div class="view-switcher ui-bar-a">
        @if (ViewContext.HttpContext.GetOverriddenBrowser().IsMobileDevice)
        {
            @: Displaying mobile view
            @Html.ActionLink("Desktop view", "SwitchView", "ViewSwitcher", new { mobile = false, returnUrl = Request.Url.PathAndQuery }, new { rel = "external" })
        } 
        else 
        {
            @: Displaying desktop view
            @Html.ActionLink("Mobile view", "SwitchView", "ViewSwitcher", new { mobile = true, returnUrl = Request.Url.PathAndQuery }, new { rel = "external" })
        }
    </div>
}